$$
\begin{array}{lll}
\left\{ \begin{array}{rl} x + y & = 1 \\ 2x - y & = -1 \end{array} \right. &\longrightarrow &\tilde{A} \vec{x} = \vec{b} \\
\left\{ \begin{array}{rl} -2x + y & = 2 \\ x - y & = -1 \end{array} \right. &\longrightarrow &\tilde{B} \vec{x} = \vec{c} \\
\left\{ \begin{array}{rl} x - 2y & = 0 \\ 2x + y & = 2 \end{array} \right. &\longrightarrow &\tilde{C} \vec{x} = \vec{d} \\
\left\{ \begin{array}{rl} 2x + 2y & = 2 \\ x - y & = 1 \end{array} \right. &\longrightarrow &\tilde{D} \vec{x} = \vec{f} \\
\left\{ \begin{array}{rl} -x + y & = 1 \\ 2x + y & = -2 \end{array} \right. &\longrightarrow &\tilde{E} \vec{x} = \vec{g} \\
\left\{ \begin{array}{rl} 2x - y & = 0 \\ x + y & = 2 \end{array} \right. &\longrightarrow &\tilde{F} \vec{x} = \vec{h} \\
\left\{ \begin{array}{rl} x + y & = 0 \\ -2x + y & = 1 \end{array} \right. &\longrightarrow &\tilde{G} \vec{x} = \vec{j} \\
\left\{ \begin{array}{rl} x - y & = -2 \\ 2x + y & = 1 \end{array} \right. &\longrightarrow &\tilde{H} \vec{x} = \vec{k} \\
\left\{ \begin{array}{rl} -2x + 2y & = 2 \\ x + y & = 1 \end{array} \right. &\longrightarrow &\tilde{J} \vec{x} = \vec{l} \\
\left\{ \begin{array}{rl} x + 2y & = 0 \\ -2x + y & = 1 \end{array} \right. &\longrightarrow &\tilde{K} \vec{x} = \vec{m}
\end{array}
$$

In [1]:
import numpy as np


matrix_A = np.array([[1, 1], [2, -2]])
matrix_B = np.array([[2, 1], [1, -1]])

print(matrix_A + matrix_B)
print(matrix_A - matrix_B)
print(np.matmul(matrix_A, matrix_B))

[[ 3  2]
 [ 3 -3]]
[[-1  0]
 [ 1 -1]]
[[3 0]
 [2 4]]


In [4]:
matrix_C = np.array([[1, -2], [2, 1]])
matrix_D = np.array([[2, 2], [1, -1]])


print(f'C = {matrix_C}\n')
print(f'D = {matrix_D}\n')

print(f'C+D = {matrix_C + matrix_D}\n')
print(f'C-D = {matrix_C - matrix_D}\n')
print(f'C D = {np.matmul(matrix_C, matrix_D)}\n')

C = [[ 1 -2]
 [ 2  1]]

D = [[ 2  2]
 [ 1 -1]]

C+D = [[3 0]
 [3 0]]

C-D = [[-1 -4]
 [ 1  2]]

C D = [[0 4]
 [5 3]]



In [5]:
matrix_E = np.array([[-1, 1], [2, 1]])
matrix_F = np.array([[2, -1], [1, 1]])

print(f'E = {matrix_E}\n')
print(f'F = {matrix_F}\n')

print(f'E+F = {matrix_E + matrix_F}\n')
print(f'E-F = {matrix_E - matrix_F}\n')
print(f'E F = {np.matmul(matrix_E, matrix_F)}\n')


E = [[-1  1]
 [ 2  1]]

F = [[ 2 -1]
 [ 1  1]]

E+F = [[1 0]
 [3 2]]

E-F = [[-3  2]
 [ 1  0]]

E F = [[-1  2]
 [ 5 -1]]



In [7]:
def print_matrix_combination(matrix_one, matrix_two, matrix_names):
    """ Takes two matrices and their names and prints out the sum, difference, and product

    :argument
    matrix_one :: np.array
    matrix_two :: np.array
    matrix_names :: list of strings

    return: None
    """


    print(f'{matrix_names[0]} = {matrix_one}\n')
    print(f'{matrix_names[1]} = {matrix_two}\n')

    print(f'{matrix_names[0]} + {matrix_names[1]} = {matrix_one + matrix_two}\n')
    print(f'{matrix_names[0]} - {matrix_names[1]} = {matrix_one - matrix_two}\n')
    print(f'{matrix_names[0]} {matrix_names[1]} = {np.matmul(matrix_one, matrix_two)}\n')

    return

matrix_G = np.array([[1, 1], [-2, 1]])
matrix_H = np.array([[1, -1], [2, 1]])
GH_names = ['G', 'H']

print_matrix_combination(matrix_G, matrix_H, GH_names)

G = [[ 1  1]
 [-2  1]]
H = [[ 1 -1]
 [ 2  1]]
G + H = [[2 0]
 [0 2]]
G - H = [[ 0  2]
 [-4  0]]
G H = [[3 0]
 [0 3]]
